### ISSUE TITLE
Find a better name for "TransactionIntent"

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-specs#16]
Since an intent would mean "I want to send this much to that account", "I want to call this function of that contract" (higher level, user-centric).

- `TransactionFuture, IntendedTransaction, TransactionFormula, TransactionSpecification, TransactionRecipe`.
- `TransactionPrecursor, TransactionCore`
- `TransactionDraft`

**Comment by ccorcoveanu** [comment]
Why do we have to complicate it? Wouldn't be enough to just have `Transaction` and `TransactionOutcome`?

**Comment by iulianpascalau** [comment]
I would go with `DraftTransaction`. `TransactiionSpecification` tells me that it is a complete (final) struct
Draft tells me that is not final and I can still work on it

**Comment by CiprianDraghici** [comment]
My proposal is `PartialTransaction`. This tells you that the object is not ready to be sent, but at the same time, the object contains the base transaction fields

**Comment by andreibancioiu** [comment]
Upon internal brainstorming, we've decided to drop the `TransactionIntent` concept (as a first choice), and adjust the transaction factories to return actual `Transaction` objects, even though they are incomplete -  e.g. `data`, `gasLimit` being properly set, while `nonce`, `chainID` not.

Motivation: less concepts leads to less confusion for developers. This choice is also consistent with other SDKs on other chains.

Downside of decision: unfortunately, incomplete transactions might cause confusion on their side.

**However,** implementing libraries can opt to return `DraftTransaction` from transaction factories, if desired (second choice). See https://github.com/multiversx/mx-sdk-specs/pull/19.
